imie = input("Podaj swoje imię: ")
nazwisko = input("Podaj swoje nazwisko: ")
tel = input("Podaj swój numer telefonu: ")
tel = tel.replace('-', '').replace(' ', '')
print("Nazywasz się {} {} i można do Ciebie zadzwonić na numer {}".format(imie.title(), nazwisko.title(), tel.strip()))
print("Czy jesteś kobietą:", imie.endswith("a"))
personal = "{} {} {}".format(imie.title(), nazwisko.title(), tel.strip())
print(len(personal))
print(len(personal[-9:]))